name: examples workflow
on:
  push:

jobs:
  default-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run test
        run: pnpm dlx jest --shard=${{ matrix.shard }}
        working-directory: examples/default-jest

  use-tenbin-jest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3]
        shardTotal: [3]
        directory:
          - examples/basic-jest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run build
        run: pnpm run build
      - name: Restore tenbin-report.json
        uses: actions/cache/restore@v4
        with:
          path: tenbin-report.json
          key: tenbin-report
      - name: Run test
        run: pnpm dlx jest --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        working-directory: ${{ matrix.directory }}
      - name: Upload tenbin-report.json
        uses: actions/upload-artifact@v4
        with:
          name: tenbin-report-${{ matrix.shardIndex }}
          path: ${{ matrix.directory }}/tenbin-report.json

  merge-and-cache-test-duration:
    runs-on: ubuntu-latest
    needs: [use-tenbin-jest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: tenbin-report
          pattern: tenbin-report-*
      - name: Merge  tenbin-report
        run: jq -s add tenbin-report/**/tenbin-report.json > tenbin-report.json
      - name: Cache tenbin-report.json
        if: ${{ github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: tenbin-report.json
          key: tenbin-report
